### ISSUE TITLE
change circle in stack to be clickable

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/12_take_save_display#3]
![image](https://user-images.githubusercontent.com/5799860/182481974-76d197f1-4c12-479a-9f27-98a06b29dc95.png)

One idea is to use an inkwell as an alternative to the iconButton.  

I have not tested this.

**Comment by caitlynbakery** [comment]
Alright I'll try it out.

**Comment by caitlynbakery** [comment]
I changed the icon to be clickable by wrapping it with an InkWell. Here's the commit for the change: 03420c3e1c4b7f06f923dddce4af9c2840adf4a8
