### ISSUE TITLE
add icon to app launcher

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/12_take_save_display#4]
Create Flutter icon for the launcher screen.  Research tutorials.  Consider using the package below.

https://pub.dev/packages/flutter_launcher_icons

**Comment by caitlynbakery** [comment]
Ok I'll look into it.

**Comment by caitlynbakery** [comment]
![Screen Shot 2022-08-03 at 2 16 04 PM](https://user-images.githubusercontent.com/22283010/182870553-40f4c478-47f1-43d1-8828-f5b8aec12317.png)

**Comment by jcasman** [comment]
I like the custom icon. Is the technique for making an icon and controlling the size and controlling the background color clear? Is it done through Android Studio? If needed, you can do this "next time"?

**Comment by codetricity** [comment]
I'm not sure what the process is, but did you see that she updated 12_take_save_display to support iOS and also made the icons for the iPhone?  So, I'm not sure if it's related to Android Studio.  She seems to have got it to work with iPhone pretty quickly.

https://github.com/caitlynbakery/12_take_save_display

![image](https://user-images.githubusercontent.com/5799860/183524623-50d76e48-c6df-45c8-9d70-554ad0b5f595.png)

**Comment by caitlynbakery** [comment]
> I like the custom icon. Is the technique for making an icon and controlling the size and controlling the background color clear? Is it done through Android Studio? If needed, you can do this "next time"?

I used the flutter package [flutter_launcher_icon](https://pub.dev/packages/flutter_launcher_icons) to add the icon which made the process fairly simple. In order to make it bigger, I used the website linked [here](https://appicon.co/). The website generated different-sized icons that I replaced to make the app icon larger. In the future, I'll be able to implement it.

**Comment by caitlynbakery** [comment]
> he iPhone? So, I'm not sure if it's related to Android Studio. She seems to have got it to work with iPhone pretty quickly.

Since I'm using the flutter_luancher_icon package it adapted to ios.

**Comment by codetricity** [comment]
nice, that package is useful!
