### ISSUE TITLE
build release version of apk

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/12_take_save_display#5]
instead of `flutter run -d name-of-device`, try `flutter build apk`

![image](https://user-images.githubusercontent.com/5799860/182493779-376058e5-8c93-4184-a13a-d73e6b2a209f.png)

you may need to adjust the http settings

https://stackoverflow.com/questions/64172791/flutter-insecure-http-is-not-allowed-by-platform

and also enable INTERNET

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.take_save_display_12">
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
```

```
08-02 16:22:05.341  4764  4789 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = 192.168.1.1, port = 80
```

After you finalize the feature set and icon, do a build.

![image](https://user-images.githubusercontent.com/5799860/182490812-9589af30-7256-41e8-b790-4394bb7e50cc.png)

you should be able to install the apk on a physical device with 

<img width="566" alt="image" src="https://user-images.githubusercontent.com/5799860/182491753-25cac807-a0f0-49d6-87e3-574a361da043.png">

**Comment by caitlynbakery** [comment]
Here's my first attempt: https://drive.google.com/file/d/1_nNZDO7eirr5-u14oq8LlWmTjgjzKrFQ/view?usp=sharing

**Comment by codetricity** [comment]
Look at

* name of app on Android launcher (I think it may be in the `AndroidManifest.xml`
* versioning of app
* release

**Comment by caitlynbakery** [comment]
Here's the link to version 1 of the project: https://github.com/caitlynbakery/12_take_save_display/releases/tag/v1.0.0

**Comment by codetricity** [comment]
Looks good.  There's additional information on updating the version number of the app here:

https://docs.flutter.dev/deployment/android#updating-the-apps-version-number
