### ISSUE TITLE
using context in async function

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/12_take_save_display#6]
Code is showing a warning about accessing BuildContext after await.

https://github.com/caitlynbakery/12_take_save_display/blob/178f0c3324c4dec5fa8febbc9963426f7da6db6c/lib/main.dart#L80

One solution to the warning is to save the context in a variable ahead of await.

https://stackoverflow.com/questions/69466478/waiting-asynchronously-for-navigator-push-linter-warning-appears-use-build/69512692#69512692

```dart
                    IconButton(
                        onPressed: () async {
                          final thetaBlocContext = context.read<ThetaBloc>();
                          final image = await ImagePicker().pickImage(
                            source: ImageSource.gallery,
                          );
                          if (image == null) return;
                          thetaBlocContext.add(ImagePickerEvent(image));
                        },
```

**Comment by caitlynbakery** [comment]
Ok, thanks for the fix!

**Comment by jcasman** [comment]
Nice work!
